import { describe, expect, it } from 'vitest';
import { generateCorpus, measureDelayAccuracy, type Scenario } from './ground-truth';

/**
 * How accurate the delay estimates are, measured against traces whose answers
 * are known by construction. Regenerated by scripts/ground-truth/report.ts.
 *
 * These are a baseline, not a target. The assertions below fail on regression
 * against them rather than against an absolute standard, because an absolute
 * threshold on a statistical estimator is either loose enough to catch nothing
 * or tight enough to flake.
 *
 * Recorded 2026-08-19 over 500 scenarios:
 *
 *   detection    100.0% of stops above the 2 s floor, 0 false positives
 *   median error 0.53 s
 *   p90 error    1.08 s
 *   max error    1.73 s
 *   bias         -0.51 s
 *
 * ## Finding: the estimator is fragile to missing speed
 *
 * Those numbers hold because this recorder reports a speed on every sample --
 * 0 of 9701 missing, per scripts/ground-truth/measure-noise.ts. Drop a tenth of
 * them and the median error goes from 0.53 s to 6.86 s, with a bias of -7.22 s.
 *
 * The cause is effectiveSpeed's positional fallback. With no reported speed it
 * differences positions, and 2.3 m of scatter over a 1 s interval reads as
 * about 3 m/s -- six times the 0.5 m/s stationary threshold. A stopped vehicle
 * therefore appears to move, and its stop is broken into pieces that each fall
 * under the 2 s floor.
 *
 * Latent rather than live: at a 0% dropout rate the fallback never runs.
 * Resolving it properly means deciding what to do when a displacement is
 * smaller than the measurement noise, where standing still and creeping at
 * 1 m/s are genuinely indistinguishable in one second of fixes. Left as a
 * finding, which is what a ground-truth harness is for.
 */
const BASELINE = {
  detectionRate: 1.0,
  falsePositives: 0,
  medianAbsError: 0.53,
  p90AbsError: 1.08,
  maxAbsError: 1.73,
  bias: -0.51,
};

// Generated once: 500 scenarios through analyzeIntersections is the expensive
// part of this file.
const corpus = generateCorpus(500);
const report = measureDelayAccuracy(corpus);

describe('delay accuracy against known truth', () => {
  it('finds every stop long enough to be findable, and invents none', () => {
    expect(report.detected / report.detectable).toBeGreaterThanOrEqual(BASELINE.detectionRate);
    expect(report.falsePositives).toBeLessThanOrEqual(BASELINE.falsePositives);
  });

  it('holds its median error', () => {
    // A tenth of a second of slack: enough that an unrelated refactor does not
    // fail, small relative to the quantities being measured.
    expect(report.medianAbsError).toBeLessThanOrEqual(BASELINE.medianAbsError + 0.1);
  });

  it('holds its tail', () => {
    expect(report.p90AbsError).toBeLessThanOrEqual(BASELINE.p90AbsError + 0.25);
    expect(report.maxAbsError).toBeLessThanOrEqual(BASELINE.maxAbsError + 1);
  });

  it('under-reports slightly, as 1 Hz sampling of a stop implies', () => {
    // The vehicle stops and starts between fixes, so at most a second is lost
    // at each end. Bias drifting positive would mean something else changed.
    expect(report.bias).toBeLessThanOrEqual(0);
    expect(report.bias).toBeGreaterThanOrEqual(-1.5);
  });

  it('is accurate in every scenario class, not just on average', () => {
    for (const [label, bucket] of Object.entries(report.byClass)) {
      if (bucket.detected === 0) continue;
      expect(bucket.medianAbsError, label).toBeLessThanOrEqual(1);
    }
  });
});

describe('what the number actually measures', () => {
  it('is stopped time, and falls well short of control delay', () => {
    // The page calls this "delay". It is the time the wheels were not turning,
    // which excludes the time lost braking and accelerating -- around 7 s a
    // stop at these speeds. Worth stating rather than discovering later.
    expect(report.medianAbsErrorVsControlDelay).toBeGreaterThan(5);
  });
});

describe('the queue-versus-signal confound', () => {
  // Phase 4 of the issue asks for this to be quantified rather than assumed.
  // The pipeline cannot tell a vehicle held by the signal from one held by the
  // queue ahead of it on green -- both stop at the same place for a comparable
  // time. This says what that costs.

  it('inflates how often an approach appears to stop you', () => {
    expect(report.confound.causedByQueueAlone).toBeGreaterThan(0);
    // About one detected stop in seven, for this scenario mix.
    expect(report.confound.fraction).toBeGreaterThan(0.1);
    expect(report.confound.fraction).toBeLessThan(0.2);
  });

  it('barely inflates how long it appears to hold you', () => {
    // The practical answer, and the reason this matters less than the count
    // suggests: a queue stop is short. Stop probability carries most of the
    // error, median delay almost none -- which is worth knowing now that
    // expected delay multiplies the two.
    expect(report.confound.medianQueueOnlyDelay).toBeLessThan(report.confound.medianSignalDelay / 3);
    expect(report.confound.shareOfDelay).toBeLessThan(0.06);
  });
});

describe('the harness has teeth', () => {
  // The real recorder reports a speed on every sample, so both of these need a
  // corpus that drops some. The rate is not realistic; the point is whether the
  // measurement moves when the input degrades in a way we know matters.
  const lossy = generateCorpus(500, { missingSpeedRate: 0.1 });
  const honest = measureDelayAccuracy(lossy);

  it('catches the null-speed-as-zero bug that #2 fixed', () => {
    // Reintroducing the bug for real is not an option, so the corpus is
    // degraded the way the bug degraded the reading: a missing speed treated as
    // a confirmed zero. Its signature is inventing stops where the vehicle
    // never stopped, which the corrected code does not do at all.
    const buggy = measureDelayAccuracy(lossy.map(coalesceNullSpeedToZero));
    expect(honest.falsePositives).toBe(0);
    expect(buggy.falsePositives).toBeGreaterThan(0);
  });

  it('shows how much a speed dropout costs the estimate', () => {
    // This is the harness earning its keep. Dropping a tenth of the speed
    // readings moves the median error from about half a second to about seven,
    // because effectiveSpeed falls back to differencing positions and 2.3 m of
    // scatter over a 1 s interval reads as roughly 3 m/s -- enough to break a
    // stationary run apart. See the finding recorded in the module header.
    expect(report.medianAbsError).toBeLessThan(1);
    expect(honest.medianAbsError).toBeGreaterThan(5);
    expect(honest.bias).toBeLessThan(-5);
  });
});

/** The corpus as the pre-#2 code would have read it. */
function coalesceNullSpeedToZero(scenario: Scenario): Scenario {
  return {
    ...scenario,
    drive: {
      ...scenario.drive,
      points: scenario.drive.points.map((point) => ({ ...point, speed: point.speed ?? 0 })),
    },
  };
}
